JUnit tests for create user
kookouri/ECSE-428-05 pull request #40
Opened 2024-10-22 17:24 UTC by julia-b-grenier

Created the UserServiceTest.
Added the Create User test

2024-10-22 18:15 UTC, ZEric2407 commented
lgtm, but will you add tests for the invalid cases later on?

2024-10-22 19:03 UTC, linamoufarreh approved these changes
looks good :)

2024-10-23 01:19 UTC, ZEric2407 requested changes

2024-10-23 01:19 UTC, ZEric2407 commented on McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/UserServiceTest.java
> +        IllegalArgumentException e =
Correct me if I'm wrong, but I believe the IllegalArgumentException would be thrown when we're calling the userService.createUser() method rather than upon instantiation of the User object.

2024-10-23 02:38 UTC, ZEric2407 approved these changes

2024-10-23 02:38 UTC, merged