Add and remove item from cart
kookouri/ECSE-428-05 pull request #81
Opened 2024-11-10 03:02 UTC by C-Tate

2024-11-10 18:47 UTC, Blacklotus88888 commented on McGillMart/McGillMart/src/main/resources/application.properties
probably will need to remove this line at the end

2024-11-11 02:51 UTC, Blacklotus89898 approved these changes
Assuming you were able to manual test, I don't think there are anything major.

2024-11-11 02:51 UTC, Blacklotus89898 commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ShoppingController.java
> +    public ResponseEntity<String> addItemToCart(@PathVariable Integer id, @RequestBody Item item) { //should this be ItemRequestDTO?
That's probably up to you, I would recommend checking for examples in users if they already exists. Otherwise this is fine.

2024-11-11 03:36 UTC, julia-b-grenier requested changes

2024-11-11 03:36 UTC, julia-b-grenier commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ShoppingController.java
> +    @PostMapping(value={"/users/{id}/shoppingCart/add"})
I think there is like a convention or like general guideline that recommends to not use verbs in RESTful API paths so its more resource-oriented. Since its post we know you are adding something I think the URL could be like /users/{id}/shopping-cart/items

2024-11-11 03:36 UTC, julia-b-grenier commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ShoppingController.java
> +    @PostMapping(value={"/users/{id}/shoppingCart/remove"})
same comment here for the verb remove

2024-11-11 03:36 UTC, julia-b-grenier commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ShoppingController.java
> +    public ResponseEntity<String> addItemToCart(@PathVariable Integer id, @RequestBody Item item) { //should this be ItemRequestDTO?
It should be itemRequestDTO indeed

2024-11-11 03:36 UTC, julia-b-grenier commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ShoppingController.java
> +    public ResponseEntity<String> removeItemFromCart(@PathVariable Integer id, @RequestBody Item item) {
I think we could pass only the id of the item here no?

2024-11-11 03:36 UTC, julia-b-grenier commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ShoppingService.java
> +            user.get().getShoppingCart().add(item);
here you dont update the repository. I think you are suppose to save the user back to the user repository. Look at updateUser in UserService

2024-11-11 03:36 UTC, julia-b-grenier commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ShoppingService.java
> +            user.get().getShoppingCart().remove(item);
same here, you dont update the database

2024-11-11 05:00 UTC, C-Tate commented on McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ShoppingController.java
> +    public ResponseEntity<String> removeItemFromCart(@PathVariable Integer id, @RequestBody Item item) {
wasn't able to use the id here because some implementations didn't use item ids (no way for ItemRequestDTO to access the id of the item)

2024-11-11 14:54 UTC, julia-b-grenier requested changes

2024-11-12 03:19 UTC, merged